# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_novel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from threading import Thread
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1041, 733)
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        self.btn_search = QtWidgets.QPushButton(Dialog)
        self.btn_search.setGeometry(QtCore.QRect(830, 40, 93, 31))
        self.btn_search.setObjectName("btn_search")
        self.edit_search = QtWidgets.QLineEdit(Dialog)
        self.edit_search.setGeometry(QtCore.QRect(150, 40, 611, 31))
        self.edit_search.setText("")
        self.edit_search.setObjectName("edit_search")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 110, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 110, 101, 16))
        self.label_2.setObjectName("label_2")
        self.edit_log = QtWidgets.QTextEdit(Dialog)
        self.edit_log.setEnabled(True)
        self.edit_log.setGeometry(QtCore.QRect(20, 140, 401, 571))
        self.edit_log.setObjectName("edit_log")
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setGeometry(QtCore.QRect(440, 140, 581, 571))
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(185)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_search.setText(_translate("Dialog", "搜索"))
        self.label.setText(_translate("Dialog", "输出日志"))
        self.label_2.setText(_translate("Dialog", "爬取信息表，双击实现下载"))
        self.label_2.adjustSize()
        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)         ## 将tableWeight设置为只读
        self.table.setSelectionBehavior(QAbstractItemView.SelectRows)    ## 将表格设置为全部选中

    # 输出日志信息
    def print_log(self,text):
        self.edit_log.append("已爬取所有页数")
