# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_rigister.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Apply_Account(object):
    def setupUi(self, Apply_Account):
        Apply_Account.setObjectName("Apply_Account")
        Apply_Account.resize(368, 355)
        Apply_Account.setMinimumSize(QtCore.QSize(368, 355))
        Apply_Account.setMaximumSize(QtCore.QSize(368, 355))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 248, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 161, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 248, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 248, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 161, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 248, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 248, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 161, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 120, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Apply_Account.setPalette(palette)
        self.label = QtWidgets.QLabel(Apply_Account)
        self.label.setGeometry(QtCore.QRect(90, 30, 188, 53))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_ok = QtWidgets.QPushButton(Apply_Account)
        self.btn_ok.setGeometry(QtCore.QRect(40, 270, 111, 61))
        self.btn_ok.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid rgb(0,255,255);\n"
"    border-radius:5px;\n"
"   \n"
"    color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0,130,150);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Apply_Account)
        self.btn_cancel.setGeometry(QtCore.QRect(220, 270, 111, 61))
        self.btn_cancel.setMinimumSize(QtCore.QSize(111, 61))
        self.btn_cancel.setMaximumSize(QtCore.QSize(111, 61))
        self.btn_cancel.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid rgb(0,255,255);\n"
"    border-radius:5px;\n"
"   \n"
"    color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0,130,150);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.layoutWidget = QtWidgets.QWidget(Apply_Account)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 109, 301, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.staff_ID = QtWidgets.QLabel(self.layoutWidget)
        self.staff_ID.setMinimumSize(QtCore.QSize(62, 27))
        self.staff_ID.setMaximumSize(QtCore.QSize(62, 27))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.staff_ID.setFont(font)
        self.staff_ID.setStyleSheet("color: rgb(0, 170, 255);")
        self.staff_ID.setObjectName("staff_ID")
        self.gridLayout.addWidget(self.staff_ID, 0, 0, 1, 1)
        self.account = QtWidgets.QLineEdit(self.layoutWidget)
        self.account.setMinimumSize(QtCore.QSize(200, 27))
        self.account.setMaximumSize(QtCore.QSize(200, 27))
        self.account.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"\n"
"")
        self.account.setMaxLength(15)
        self.account.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.account.setObjectName("account")
        self.gridLayout.addWidget(self.account, 0, 1, 1, 1)
        self.staff_ID_4 = QtWidgets.QLabel(self.layoutWidget)
        self.staff_ID_4.setMinimumSize(QtCore.QSize(62, 27))
        self.staff_ID_4.setMaximumSize(QtCore.QSize(62, 27))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.staff_ID_4.setFont(font)
        self.staff_ID_4.setStyleSheet("color: rgb(0, 170, 255);")
        self.staff_ID_4.setObjectName("staff_ID_4")
        self.gridLayout.addWidget(self.staff_ID_4, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setMinimumSize(QtCore.QSize(200, 27))
        self.password.setMaximumSize(QtCore.QSize(200, 27))
        self.password.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"\n"
"")
        self.password.setMaxLength(15)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.staff_ID_3 = QtWidgets.QLabel(self.layoutWidget)
        self.staff_ID_3.setMinimumSize(QtCore.QSize(85, 27))
        self.staff_ID_3.setMaximumSize(QtCore.QSize(62, 27))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.staff_ID_3.setFont(font)
        self.staff_ID_3.setStyleSheet("color: rgb(0, 170, 255);")
        self.staff_ID_3.setObjectName("staff_ID_3")
        self.gridLayout.addWidget(self.staff_ID_3, 2, 0, 1, 1)
        self.password_again = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_again.setMinimumSize(QtCore.QSize(200, 27))
        self.password_again.setMaximumSize(QtCore.QSize(200, 27))
        self.password_again.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"\n"
"")
        self.password_again.setMaxLength(15)
        self.password_again.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_again.setObjectName("password_again")
        self.gridLayout.addWidget(self.password_again, 2, 1, 1, 1)

        self.retranslateUi(Apply_Account)
        QtCore.QMetaObject.connectSlotsByName(Apply_Account)

    def retranslateUi(self, Apply_Account):
        _translate = QtCore.QCoreApplication.translate
        Apply_Account.setWindowTitle(_translate("Apply_Account", "Dialog"))
        self.label.setText(_translate("Apply_Account", "申请账号"))
        self.btn_ok.setText(_translate("Apply_Account", "确认"))
        self.btn_cancel.setText(_translate("Apply_Account", "取消"))
        self.staff_ID.setText(_translate("Apply_Account", "账号:"))
        self.account.setPlaceholderText(_translate("Apply_Account", "请输入账号"))
        self.staff_ID_4.setText(_translate("Apply_Account", "密码:"))
        self.password.setPlaceholderText(_translate("Apply_Account", "请输入密码"))
        self.staff_ID_3.setText(_translate("Apply_Account", "确认密码:"))
        self.password_again.setPlaceholderText(_translate("Apply_Account", "请确认密码"))
