# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(437, 340)
        login.setMinimumSize(QtCore.QSize(437, 340))
        login.setMaximumSize(QtCore.QSize(437, 340))
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(120, 247, 200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_login.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_login.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_login.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid rgb(0,255,255);\n"
"    border-radius:5px;\n"
"   \n"
"    color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0,130,150);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.line_account = QtWidgets.QLineEdit(self.centralwidget)
        self.line_account.setGeometry(QtCore.QRect(140, 157, 200, 27))
        self.line_account.setMinimumSize(QtCore.QSize(200, 27))
        self.line_account.setMaximumSize(QtCore.QSize(200, 27))
        self.line_account.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:3px;\n"
"}\n"
"")
        self.line_account.setText("")
        self.line_account.setMaxLength(15)
        self.line_account.setObjectName("line_account")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, -3, 441, 151))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(131, 125, 184, 255), stop:0.378109 rgba(74, 134, 201, 255), stop:0.641791 rgba(51, 121, 228, 255), stop:0.975124 rgba(76, 128, 255, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btn_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_apply.setGeometry(QtCore.QRect(40, 297, 90, 28))
        self.btn_apply.setMinimumSize(QtCore.QSize(90, 28))
        self.btn_apply.setSizeIncrement(QtCore.QSize(90, 28))
        self.btn_apply.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid rgb(0,255,255);\n"
"    border-radius:5px;\n"
"   \n"
"    color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0,130,150);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        self.btn_apply.setObjectName("btn_apply")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 37, 188, 53))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.staff_ID_2 = QtWidgets.QLabel(self.centralwidget)
        self.staff_ID_2.setGeometry(QtCore.QRect(71, 200, 44, 22))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.staff_ID_2.setFont(font)
        self.staff_ID_2.setStyleSheet("color: rgb(0, 170, 255);")
        self.staff_ID_2.setObjectName("staff_ID_2")
        self.staff_ID = QtWidgets.QLabel(self.centralwidget)
        self.staff_ID.setGeometry(QtCore.QRect(71, 157, 44, 22))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.staff_ID.setFont(font)
        self.staff_ID.setStyleSheet("color: rgb(0, 170, 255);")
        self.staff_ID.setObjectName("staff_ID")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-10, 107, 471, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 241, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        self.label_3.setStyleSheet("background-color: rgb(232, 241, 252);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(140, 200, 200, 27))
        self.line_password.setMinimumSize(QtCore.QSize(200, 27))
        self.line_password.setMaximumSize(QtCore.QSize(200, 27))
        self.line_password.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(134,183,200);\n"
"    border:2px solid #5F92B2;\n"
"    border-radius:3px;\n"
"}\n"
"")
        self.line_password.setText("")
        self.line_password.setMaxLength(15)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setDragEnabled(False)
        self.line_password.setReadOnly(False)
        self.line_password.setObjectName("line_password")
        self.label_3.raise_()
        self.btn_login.raise_()
        self.line_account.raise_()
        self.label_2.raise_()
        self.btn_apply.raise_()
        self.label.raise_()
        self.staff_ID_2.raise_()
        self.staff_ID.raise_()
        self.line_password.raise_()
        # login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.btn_login.setText(_translate("login", "安全登录"))
        self.line_account.setPlaceholderText(_translate("login", "请输入账号"))
        self.btn_apply.setText(_translate("login", "申请账户"))
        self.label.setText(_translate("login", "用户登录"))
        self.staff_ID_2.setText(_translate("login", "密码:"))
        self.staff_ID.setText(_translate("login", "账号:"))
        self.line_password.setPlaceholderText(_translate("login", "请输入密码"))
